name: PR Agent

on:
  pull_request:

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    env:
      PR_AGENT_MODEL: gpt-3.5-turbo
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Tailscale
        uses: tailscale/github-action@53acf823325fe9ca47f4cdaa951f90b4b0de5bb9 # v4
        with:
          authkey: ${{ secrets.TS_AUTH_KEY }}
          tags: tag:ci
          statedir: /tmp/tailscale-state/
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@d36ad319f7fb0049205017405a71275c41599587 # v0.31
        env:
          OPENAI.API_BASE: https://litellm.stinkyboi.com/v1
          OPENAI_KEY: ${{ secrets.LITELLM_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config.model: ${{ env.PR_AGENT_MODEL }}
          config.custom_model_max_tokens: 200000
