---
name: PR Agent
on:
  pull_request:
permissions:
  issues: write
  pull-requests: write
  contents: read
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    env:
      PR_AGENT_MODEL: gpt-3.5-turbo
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Tailscale
        uses: tailscale/github-action@53acf823325fe9ca47f4cdaa951f90b4b0de5bb9 # v4
        with:
          authkey: ${{ secrets.TS_AUTH_KEY }}
          tags: tag:ci
          statedir: /tmp/tailscale-state/
      - name: Review Bot
        uses: Stuhlmuller/ai-pr-reviewer@0365077c9ba8788b44164426bda80f9e43ec2939 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: true
          review_comment_lgtm: false
          openai_heavy_model: gpt-4
          path_filters: |-
            !dist/**
            !**/*.lock
